import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#fdf8f8",
        "surface-dim": "#ddd9d8",
        "surface-bright": "#fdf8f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f3f2",
        "surface-container": "#f1edec",
        "surface-container-high": "#ebe7e6",
        "surface-container-highest": "#e5e2e1",
        "surface-variant": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#444748",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f4f0ef",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        secondary: "#615e58",
        "on-secondary": "#ffffff",
        "secondary-container": "#e7e2d9",
        "on-secondary-container": "#67645d",
        "secondary-fixed": "#e7e2d9",
        "secondary-fixed-dim": "#cbc6be",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1c1b1a",
        "on-tertiary-container": "#868382",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fdf8f8",
        "on-background": "#1c1b1b",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        gutter: "24px",
        md: "32px",
        margin: "40px",
        lg: "64px",
        xl: "128px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-inter)", "Inter", "sans-serif"],
        serif: ["Playfair Display", "Georgia", "serif"],
      },
      fontSize: {
        "display-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "500" }],
        display: ["72px", { lineHeight: "76px", letterSpacing: "-0.04em", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
